### ISSUE TITLE
get_puf_names broken

### ISSUE THREAD

**Issue by tom-pham** [e-mitchell/meps_r_pkg#7]
Hi,

I've noticed recently that `get_puf_names()` has broken for me. 

Here is my session info.

> > sessionInfo()
> R version 4.2.1 (2022-06-23)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 20.04.4 LTS
> 
> Matrix products: default
> BLAS/LAPACK: /opt/intel/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64_lin/libmkl_rt.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] MEPS_1.3.0
> 
> loaded via a namespace (and not attached):
>  [1] fansi_1.0.3      withr_2.5.0      assertthat_0.2.1 utf8_1.2.2       dplyr_1.0.10     R6_2.5.1         DBI_1.1.3       
>  [8] lifecycle_1.0.3  labelled_2.9.1   magrittr_2.0.3   pillar_1.8.1     rlang_1.0.6      cli_3.6.0        curl_4.3.2      
> [15] rstudioapi_0.13  ellipsis_0.3.2   vctrs_0.5.1      generics_0.1.3   forcats_0.5.1    tools_4.2.1      glue_1.6.2      
> [22] hms_1.1.1        compiler_4.2.1   pkgconfig_2.0.3  haven_2.5.0      tidyselect_1.2.0 tibble_3.1.8   

Testing
`get_puf_names(year = 2004)`

> Error in `dplyr::mutate()`:
> ! Problem while computing `LONG = LONGITUDINAL`.
> Caused by error in `mask$eval_all_mutate()`:
> ! object 'LONGITUDINAL' not found

**Comment by e-mitchell** [comment]
Hi Tom, 

Thanks for sending in the issue. Please make sure to re-install with the newest version of the package (released just a few days ago). I recently reconfigured the csv file that `get_puf_names ` reaches out to, to split out the Longitudinal file:

- [meps_file_names](https://github.com/HHS-AHRQ/MEPS/blob/master/Quick_Reference_Guides/meps_file_names.csv) (new version, without Longitudinal file) 
- [meps_longitudinal_file_names](https://github.com/HHS-AHRQ/MEPS/blob/master/Quick_Reference_Guides/meps_longitudinal_file_names.csv) (separate file for Longitudinal data)

I made this change because the Longitudinal files for Panels 23 and 24 have 3-year and 4-year options, so I wanted to allow users to download those files if needed.

Once you re-install, the `get_puf_names` function should work as usual.

Please let me know if you run into any more errors!
